version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file: 
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3001:3000"  # Serveur de développement frontend sur le port 3001 pour éviter un conflit
    command: npm start
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
